---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: docker
  image: livingdocs/docker-node:20.10
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  commands:
    - |
      docker-login

      SHA_TAG=livingdocs/semantic-release:sha-$DRONE_COMMIT_SHA
      docker build -t $SHA_TAG .
      docker push $SHA_TAG

      echo -----------------
      echo Docker Tag: $SHA_TAG
      echo -----------------

- name: release
  image: livingdocs/semantic-release:sha-${DRONE_COMMIT_SHA}
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [push]

---
kind: pipeline
name: docker-release
clone:
  disable: true

steps:
- name: tag
  image: livingdocs/docker-node:20.10
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  commands:
    - docker-login
    - regctl image cp livingdocs/semantic-release:sha-$DRONE_COMMIT_SHA livingdocs/semantic-release:$DRONE_TAG

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [tag]

---
kind: signature
hmac: 23a1a55f19bbe37fe9a349f20b4d9790b311e04bff88c18bc7d912dfbf9c5a91

...
